### ISSUE TITLE
$ ./bin/deploy doesn't work

### ISSUE THREAD

**Issue by sostakas** [customink/ruby-vips-lambda#19]
Hi, I think you are missing ca-certificates update. Attaching first occured error

 => ERROR [ 6/28] RUN curl -L https://downloads.sourceforge.net/libpng/li  0.7s
------
 > [ 6/28] RUN curl -L https://downloads.sourceforge.net/libpng/libpng-1.6.37.tar.xz > libpng-1.6.37.tar.xz &&     tar -xf libpng-1.6.37.tar.xz &&     cd libpng-1.6.37 &&     ./configure --prefix=/opt --disable-static &&     make &&     make install:
#10 0.225   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#10 0.225                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#10 0.686 curl: (60) SSL certificate problem: certificate has expired
#10 0.686 More details here: https://curl.haxx.se/docs/sslcerts.html
#10 0.686
#10 0.686 curl failed to verify the legitimacy of the server and therefore could not
#10 0.686 establish a secure connection to it. To learn more about this situation and
#10 0.686 how to fix it, please visit the web page mentioned above.
------

**Comment by metaskills** [comment]
Retooled the whole project. Should work now.
