### ISSUE TITLE
Build failing with latest docker image (lambda:build-ruby2.5)

### ISSUE THREAD

**Issue by mdoyle13** [customink/ruby-vips-lambda#2]
given the news today about the Lambda runtime updates(https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/)  I wanted to try out a new build to start testing some existing code.

Unfortunately, I can't get the build to work. 

Here's the error I'm seeing:

```
gcc: error: libgomp.spec: No such file or directory
make[2]: *** [introspect] Error 1
make[2]: Leaving directory `/build/libvips/libvips'
make[1]: Leaving directory `/build/libvips/libvips'
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
The command '/bin/sh -c cd ./libvips &&   ./autogen.sh   --prefix=${INSTALLDIR}   --disable-static &&   make install &&   echo /opt/lib > /etc/ld.so.conf.d/libvips.conf &&   ldconfig' returned a non-zero code: 2```

**Comment by metaskills** [comment]
Confirmed! Pulled the latest Docker images and this is the full log. https://gist.github.com/metaskills/d3b5f94dc8173991b56b6f4b205e4336

Will need a few days before I can take a look at this. I wonder if we can also look here to see if similar errors have been reported. https://github.com/lovell/sharp

**Comment by metaskills** [comment]
Maybe related. https://github.com/libvips/libvips/issues/1267

**Comment by metaskills** [comment]
OK, I can confirm this does build now. Can you try this diff and tell me how it goes for you. I'll be doing the same too soon.

```diff
--- a/Dockerfile
+++ b/Dockerfile
@@ -26,7 +26,8 @@ RUN git clone git://github.com/libvips/libvips.git && \
 RUN cd ./libvips && \
   ./autogen.sh \
   --prefix=${INSTALLDIR} \
-  --disable-static && \
+  --disable-static \
+  --without-magick && \
   make install && \
   echo /opt/lib > /etc/ld.so.conf.d/libvips.conf && \
   ldconfig
```

**Comment by metaskills** [comment]
Also, did you find builds prior to using the new Docker images had issues?

**Comment by mdoyle13** [comment]
Build works for me with that diff. Thanks for looking into it.

I was able to build successfully just a few days ago before docker-lambda updated the base image

In terms of the new docker base image -I also go it to work using clang to build. I'm not sure what the implications of using clang to build would be - but it did work.

```
--- a/Dockerfile
+++ b/Dockerfile
@@ -25,6 +25,7 @@ RUN git clone git://github.com/libvips/libvips.git && \
 #
 RUN cd ./libvips && \
   ./autogen.sh \
+  CC=clang CXX=clang++ \
   --prefix=${INSTALLDIR} \
   --disable-static && \
   make install && \
```

**Comment by metaskills** [comment]
Thanks! I've created PR #3. See there for details... will be posting more notes soon.

**Comment by mdoyle13** [comment]
Thats awesome, thanks. 

I haven't had a chance to retry (without the clang build directive) but I wonder if this commit from docker-lambda would fix the build? Just want to re-iterate im not super knowledgeable about compiling software but my gut tells me it might fix the issue with the original autogen args.

GCC version change
https://github.com/lambci/docker-lambda/commit/916e74951eb0427de334ccc9dc39bff35989fca6

and then updated again

https://github.com/lambci/docker-lambda/commit/942d7bfe95f75409937341ae325ef1c88aab029e

**Comment by metaskills** [comment]
Thanks @mdoyle13 I'm in the same boat, not super knowledgeable here. 

I got #3 merged, then saw your comment. However, I could not get anything using `alternatives` to work and compile. Thoughts?

**Comment by mdoyle13** [comment]
@metaskills - so i tried the latest with and without the clang build and both work fine for me so I'm going to close this issue. Thanks for the great project!

**Comment by mdoyle13** [comment]
hey just wanted to follow up on this one last time. not totally related to this issue but I had to rebuild with image magick for gif support. just wanted to drop that note here. thanks!

**Comment by metaskills** [comment]
@mdoyle13 That's very very good feedback. I'm not doing GIFs, but I think that calls for a change. I've pushed the removal to disable ImageMagick to master. Thanks!!! https://github.com/customink/ruby-vips-lambda/commit/7d89fd140a7cf0a2033f39853bcbb489516338ae
