### ISSUE TITLE
VipsForeignLoad for pdfs

### ISSUE THREAD

**Issue by benbonnet** [customink/ruby-vips-lambda#6]
Hello, while trying to open pdf file (to convert those to image), I'm stuck at this point :

```
{
    "errorMessage": "VipsForeignLoad: \"/path/to/pdf/file.pdf\" is not a known file format\n",
    "errorType": "Function<Vips::Error>",
    "stackTrace": [
        "/opt/2.5.0/gems/ruby-vips-2.0.16/lib/vips/image.rb:255:in `new_from_file'",
        "/var/task/image_processing/split_images.rb:27:in `process'",
        "/var/task/image_processing/index.rb:7:in `process'"
    ]
}
```

I've read around that it has to do with ghost script; while i can't really be sure of it (tried to exend the Dockerfile with a yum install ghostscript, no success)

Does this error speaks to you ? Can it be solved ?

**Comment by metaskills** [comment]
Hey Ben, thanks for using this project! I was searching here (https://libvips.github.io/libvips/install.html) for mentions of "pdf" and found a few lines. A few thoughts or options, first, have you tried installing `poppler-glib` or are you relying on `imagemagick`?

**Comment by benbonnet** [comment]
I've found out that lambda provides image magick by default (preinstalled), but obviously it does not helps here

For now i dont really know where to start; do i need an extra layer; or can i extend the dockerfile you provide ?

**Comment by metaskills** [comment]
Definitely clone the repo and change the Docker file to suite your needs. Also, I thought imagemagick was removed on all runtimes during the update in July?

**Comment by benbonnet** [comment]
Probably i havent followed much what happened

Ok, just to make sure; you only copy the libvips*.so at the end right ? How can i make sure everything (vips and imagemagick) ends up in the layer ? Am having a little hard time to get how things are available at the end in the layer

**Comment by metaskills** [comment]
I hear ya, I'm not expert at this either. I tend to do a docker run into the container and play around and find the right commands and installed libs. At the end of the day everything has to be installed to the /opt dir.

**Comment by benbonnet** [comment]
hehe quite hard o get into it. if I may ask, which folder (the one where things gets installed in the image - via the yum installs) should be brought to the layer opt dir ?

**Comment by metaskills** [comment]
Typical the `.so` files

**Comment by metaskills** [comment]
Do post or share some notes if you worked this out.

**Comment by benbonnet** [comment]
I will as soon as I can! I assumed it was not exactly an issue in the end

**Comment by metaskills** [comment]
Yes, not an issue per se. More of like a variant of this base layer which aims to be small. IE, if you solve it, I would very much like to add some notes to the README on how other's could do the same. Seems very valid.
