### ISSUE TITLE
The layer name isn't the version I've packaged

### ISSUE THREAD

**Issue by tomharvey** [customink/ruby-vips-lambda#9]
I noticed that my layer is published as `rubyvips891` after running `VIPS_VERSION=8.9.2 bin/deploy` and it looks like it checked out 8.9.2 of libvips from GitHub (I _think_ it respected my version target but I've yet to dig into that).

Is the layer name supposed to reflect the version of libvips?

I'd be more than happy to PR that if it's an error.

I'm already proud that I thought - "stop, search to see if some has made" this before I started to burn an evening with Dockerfiles. Big thanks to you guys at custom ink!

**Comment by metaskills** [comment]
Thanks! I think the layer name should reflect the semantic version. So a pull request to fix that would be appreciated. The env would be used here (https://github.com/customink/ruby-vips-lambda/blob/master/bin/deploy#L8) Maybe to make that DRY the first thing the build should do form the Dockerfile is write out a `.version` file or something using the ENV it got?

**Comment by metaskills** [comment]
Fixed in #10
